name: Update subconverter

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'commit message'
        required: true
        default: 'Update subconverter'
   
jobs:
  Build:
    name: Build and Update
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare
      run: |
        cd /tmp
        git clone https://github.com/tindy2013/subconverter.git
    - name: Build
      run: docker run -v /tmp/subconverter:/root/workdir multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Clean up
      run: |
        sudo rm -rf subconverter
        mv -f /tmp/subconverter/subconverter subconverter
        mv -f subconverter/subconverter subconverter/subconverter.exe
        sudo chmod +x subconverter/subconverter.exe
    - name: Modify pref.ini
      run: |
        cp -f subconverter/pref.example.ini subconverter/pref.ini
        sed -i 's/api_mode=false/api_mode=true/g' subconverter/pref.ini
        sed -i 's/managed_config_prefix=http:\/\/127.0.0.1:25500/managed_config_prefix=https:\/\/sub-beta.now.sh/g' subconverter/pref.ini
        sed -i 's/async_fetch_ruleset=false/async_fetch_ruleset=true/g' subconverter/pref.ini
        sed -i 's/max_concurrent_threads=./max_concurrent_threads=1/g' subconverter/pref.ini
    - name: Add & Commit
      uses: EndBug/add-and-commit@v6
      with:
        author_name: GitHub Action
        author_email: noreply@github.com
        message: ${{ github.event.inputs.message }}
        add: "-A"
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
