name: Update sub-web

on:
  workflow_dispatch:
  push:
    paths:
    - 'subconverter/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Update sub-web
      run: |
        rm -rf sub-web
        git clone https://github.com/zhongfly/sub-web.git

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get dependencies and build
      run: |
        cd sub-web
        yarn install
        yarn build
        
    - name: Clean up
      run: |
        cd $GITHUB_WORKSPACE
        mkdir temp
        sudo cp -rf sub-web/dist/* temp/
        sudo rm -rf sub-web
        mv temp sub-web
        
    - name: Check subconverter
      run: |
        sudo chmod +x subconverter/subconverter.exe
        sed -i 's/api_mode=false/api_mode=true/g' subconverter/pref.ini
        sed -i 's/managed_config_prefix=http:\/\/127.0.0.1:25500/managed_config_prefix=https:\/\/sub-beta.now.sh/g' subconverter/pref.ini
        sed -i 's/async_fetch_ruleset=false/async_fetch_ruleset=true/g' subconverter/pref.ini
        sed -i 's/max_concurrent_threads=./max_concurrent_threads=1/g' subconverter/pref.ini
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        author_name: GitHub Action
        author_email: noreply@github.com
        message: "Update sub-web from zhongfly/sub-web"
        add: "-A"
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }} 
